version: '3.9'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GOOGLE_SHEETS_API_KEY=${GOOGLE_SHEETS_API_KEY}
    container_name: main
    command: npm start